import type { CSSProperties } from "react";

/** Grid columns for the fleet table: Agent | Accept | Runs | Findings | Cost | Trend. */
export const GRID = "2fr 90px 70px 100px 110px 110px";

/** Co-located styles for AgentPerformanceView. */
export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1200, margin: "0 auto" } satisfies CSSProperties,
  header: { marginBottom: 22 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { fontSize: 14, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,

  kpiRow: { display: "flex", gap: 12, marginBottom: 24, flexWrap: "wrap" } satisfies CSSProperties,
  kpiCardWrap: { flex: 1, minWidth: 200 } satisfies CSSProperties,
  mostActiveValue: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  mostActiveName: {
    fontSize: 20,
    fontWeight: 700,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 180,
  } satisfies CSSProperties,
  mostActiveSub: { fontSize: 12, fontWeight: 500, color: "var(--text-muted)" } satisfies CSSProperties,

  sectionLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: 12,
  } satisfies CSSProperties,

  donutsRow: { display: "flex", gap: 20, flexWrap: "wrap", marginBottom: 28 } satisfies CSSProperties,
  donutCard: {
    flex: 1,
    minWidth: 260,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    padding: "16px 20px",
  } satisfies CSSProperties,
  donutHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: 14,
  } satisfies CSSProperties,
  noCost: { fontSize: 12, color: "var(--text-muted)", padding: "20px 0", textAlign: "center" } satisfies CSSProperties,
  unknownList: { display: "flex", flexDirection: "column", gap: 6, marginTop: 10 } satisfies CSSProperties,
  unknownRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 13 } satisfies CSSProperties,
  unknownDot: {
    width: 9,
    height: 9,
    borderRadius: 2,
    background: "var(--text-muted)",
    opacity: 0.4,
    flexShrink: 0,
  } satisfies CSSProperties,
  unknownLabel: { color: "var(--text-secondary)", flex: 1 } satisfies CSSProperties,
  unknownValue: { color: "var(--text-muted)" } satisfies CSSProperties,

  tableCard: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  filterBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
    padding: "14px 20px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  filterItem: { minWidth: 160 } satisfies CSSProperties,
  headRow: {
    display: "grid",
    gridTemplateColumns: GRID,
    gap: 14,
    padding: "10px 20px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  row: {
    display: "grid",
    gridTemplateColumns: GRID,
    alignItems: "center",
    gap: 14,
    padding: "12px 20px",
    borderBottom: "1px solid var(--border)",
    cursor: "pointer",
  } satisfies CSSProperties,
  agentCell: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 } satisfies CSSProperties,
  agentIconBox: {
    width: 28,
    height: 28,
    borderRadius: 7,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  agentText: { minWidth: 0 } satisfies CSSProperties,
  cellPrimary: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "block",
  } satisfies CSSProperties,
  cellSecondary: {
    fontSize: 11,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    marginTop: 2,
  } satisfies CSSProperties,
  muted: { color: "var(--text-muted)" } satisfies CSSProperties,
  loadingStack: { padding: 20, display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
} as const;
