import type { CSSProperties } from "react";

/** Co-located styles for the skill EvalsTab and its sub-components. Vocabulary
    differs from the agent-eval EvalsTab (judge score / grounding pass rate /
    cases passing) but the layout patterns are copied from that precedent. */
export const s = {
  wrap: { padding: "24px 28px" } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  title: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: 10,
    marginTop: 28,
  } satisfies CSSProperties,
  passingBadge: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--ok)",
    background: "var(--ok-bg)",
    padding: "2px 8px",
    borderRadius: 999,
  } satisfies CSSProperties,
  runControls: {
    display: "flex",
    alignItems: "flex-end",
    gap: 8,
    marginBottom: 20,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowName: { fontWeight: 600, fontSize: 13 } satisfies CSSProperties,
  rowSubtitle: {
    fontSize: 11,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowActions: { display: "flex", gap: 4, flexShrink: 0 } satisfies CSSProperties,
  metaChip: {
    fontSize: 11,
    color: "var(--text-secondary)",
    whiteSpace: "nowrap",
    flexShrink: 0,
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
  } satisfies CSSProperties,
  iconAction: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    color: "var(--text-muted)",
    display: "inline-flex",
  } satisfies CSSProperties,
  // ---- metrics strip ------------------------------------------------------
  metricsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  } satisfies CSSProperties,
  metricsTitle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  metricsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 10,
    marginBottom: 20,
  } satisfies CSSProperties,
  metricCard: {
    padding: "12px 14px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 10,
  } satisfies CSSProperties,
  metricLabel: {
    fontSize: 10.5,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  metricValue: {
    fontSize: 24,
    fontWeight: 700,
    lineHeight: 1.1,
  } satisfies CSSProperties,
  // ---- batch history table ------------------------------------------------
  table: { width: "100%", borderCollapse: "collapse", fontSize: 12.5 } satisfies CSSProperties,
  th: {
    textAlign: "left",
    padding: "8px 10px",
    color: "var(--text-muted)",
    fontWeight: 600,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.03em",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  td: {
    padding: "8px 10px",
    borderBottom: "1px solid var(--border)",
    verticalAlign: "middle",
  } satisfies CSSProperties,
  note: {
    fontSize: 12,
    color: "var(--text-muted)",
    padding: "8px 12px",
    background: "var(--bg-hover)",
    borderRadius: 6,
    marginBottom: 12,
  } satisfies CSSProperties,
  // ---- batch history: row select / drill-down (ported from agent-eval) ----
  batchRow: { cursor: "pointer" } satisfies CSSProperties,
  drilldownWrap: {
    padding: "12px 14px",
    background: "var(--bg-hover)",
    borderRadius: 6,
    margin: "6px 0 12px",
  } satisfies CSSProperties,
  caseErrorMessage: {
    marginTop: 4,
    fontSize: 11,
    color: "var(--crit)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 320,
  } satisfies CSSProperties,
  // ---- Case Editor ---------------------------------------------------------
  editorBody: { padding: "18px 22px", display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  fieldLabel: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  smallLabel: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  sectionSubLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  listEditorRow: { display: "flex", gap: 8, alignItems: "center" } satisfies CSSProperties,
  errorBanner: {
    fontSize: 12.5,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    padding: "8px 22px",
  } satisfies CSSProperties,
} as const;
