import type { CSSProperties } from "react";

/** Co-located styles for StatsTab. */
export const s = {
  wrap: { padding: "24px 28px" } satisfies CSSProperties,
  sectionLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginTop: 28,
    marginBottom: 10,
  } satisfies CSSProperties,
  approxBadge: {
    fontSize: 10,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    padding: "1px 7px",
    borderRadius: 999,
    textTransform: "none",
    letterSpacing: "normal",
  } satisfies CSSProperties,
  tileGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 12,
  } satisfies CSSProperties,
  tile: {
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "14px 16px",
  } satisfies CSSProperties,
  tileLabel: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: 8,
  } satisfies CSSProperties,
  tileValue: { fontSize: 22, fontWeight: 700 } satisfies CSSProperties,
  tileUnit: { fontSize: 13, marginLeft: 2, color: "var(--text-secondary)" } satisfies CSSProperties,
  circularWrap: { display: "flex", alignItems: "center", minHeight: 48 } satisfies CSSProperties,
  mutedDash: { fontSize: 22, fontWeight: 700, color: "var(--text-muted)" } satisfies CSSProperties,
  costCard: { marginTop: 4, maxWidth: 320 } satisfies CSSProperties,
  severityRow: { display: "flex", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  rankedList: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  rankedEmpty: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    padding: "12px 0",
  } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 12.5 } satisfies CSSProperties,
  th: {
    textAlign: "left",
    padding: "8px 10px",
    color: "var(--text-muted)",
    fontWeight: 600,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.03em",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  td: {
    padding: "8px 10px",
    borderBottom: "1px solid var(--border)",
    verticalAlign: "middle",
  } satisfies CSSProperties,
  row: { cursor: "pointer" } satisfies CSSProperties,
  loadingWrap: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
} as const;
