import type { CSSProperties } from "react";

/** Co-located styles for the 4-step Export Wizard. */
export const s = {
  stepsWrap: { padding: "16px 24px 4px" } satisfies CSSProperties,
  stepBody: { padding: "16px 24px 24px", display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  conflictBox: {
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 13,
  } satisfies CSSProperties,
  targetGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 } satisfies CSSProperties,
  targetCardActive: {
    textAlign: "left",
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--accent)",
    background: "var(--accent-bg)",
    cursor: "default",
  } satisfies CSSProperties,
  targetCardDisabled: {
    textAlign: "left",
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    opacity: 0.5,
    cursor: "not-allowed",
  } satisfies CSSProperties,
  targetCardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    marginBottom: 4,
  } satisfies CSSProperties,
  targetCardDesc: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  noRepoHint: { fontSize: 13, color: "var(--text-muted)", padding: "10px 12px" } satisfies CSSProperties,
  filesToCreate: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: 4,
  } satisfies CSSProperties,
  filePath: { fontSize: 12, fontFamily: "var(--font-mono, monospace)", color: "var(--text-secondary)" } satisfies CSSProperties,
  readonlyFile: {
    margin: 0,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-primary)",
    color: "var(--text-secondary)",
    fontSize: 12,
    maxHeight: 280,
    overflow: "auto",
    whiteSpace: "pre-wrap",
  } satisfies CSSProperties,

  /* --- Preview: two-column (file list | content viewer) --- */
  previewGrid: { display: "grid", gridTemplateColumns: "220px 1fr", gap: 14, alignItems: "start" } satisfies CSSProperties,
  previewList: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0 } satisfies CSSProperties,
  previewListItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    padding: "7px 10px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-secondary)",
    transition: "background .12s, border-color .12s",
  } satisfies CSSProperties,
  previewListItemActive: {
    background: "var(--accent-bg)",
    border: "1px solid var(--accent)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  previewListPath: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 11.5,
    wordBreak: "break-all",
    lineHeight: 1.4,
  } satisfies CSSProperties,
  previewViewer: { display: "flex", flexDirection: "column", gap: 8, minWidth: 0 } satisfies CSSProperties,
  previewViewerHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  } satisfies CSSProperties,

  /* --- Configure: trigger pills, post-as radios, fail-CI info box --- */
  pillRow: { display: "flex", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  radioGroup: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  radioItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "9px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    cursor: "pointer",
    textAlign: "left",
    fontSize: 13,
    transition: "border-color .12s, background .12s",
  } satisfies CSSProperties,
  radioItemActive: { border: "1px solid var(--accent)", background: "var(--accent-bg)" } satisfies CSSProperties,
  radioDot: {
    width: 16,
    height: 16,
    borderRadius: 99,
    border: "2px solid var(--border-strong)",
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  } satisfies CSSProperties,
  radioDotActive: { border: "2px solid var(--accent)" } satisfies CSSProperties,
  radioDotInner: { width: 8, height: 8, borderRadius: 99, background: "var(--accent)" } satisfies CSSProperties,
  radioText: { display: "flex", flexDirection: "column", gap: 1 } satisfies CSSProperties,
  radioLabel: { fontWeight: 500, color: "var(--text-primary)" } satisfies CSSProperties,
  infoBox: {
    display: "flex",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  infoIcon: { color: "var(--text-muted)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,

  /* --- Install: two choice cards + docs link --- */
  installCard: {
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  installCardTitle: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  installCardBody: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  installChoicePrimary: {
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--accent)",
    background: "var(--accent-bg)",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  installChoiceHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  installChoiceZip: {
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  } satisfies CSSProperties,
  installZipTitle: { fontSize: 13, fontWeight: 500, display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  installZipHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  installDocs: { fontSize: 12.5, color: "var(--text-muted)", textAlign: "center", paddingTop: 2 } satisfies CSSProperties,
  installDocsLink: { color: "var(--accent-text)" } satisfies CSSProperties,

  installResult: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  installResultRow: { fontSize: 13 } satisfies CSSProperties,
  secretRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  secretValue: {
    flex: 1,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-primary)",
    color: "var(--text-primary)",
    fontSize: 12,
    overflow: "auto",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  footerRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
} as const;
