import type { CSSProperties } from "react";

/** Co-located styles for the EvalsTab and its sub-components. */
export const s = {
  wrap: { padding: "24px 28px" } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  } satisfies CSSProperties,
  titleRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  title: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: 10,
    marginTop: 28,
  } satisfies CSSProperties,
  note: {
    fontSize: 12,
    color: "var(--text-muted)",
    padding: "8px 12px",
    background: "var(--bg-hover)",
    borderRadius: 6,
    marginBottom: 12,
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: 8,
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowName: { fontWeight: 600, fontSize: 13 } satisfies CSSProperties,
  rowSubtitle: {
    fontSize: 11,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowActions: { display: "flex", gap: 4, flexShrink: 0 } satisfies CSSProperties,
  iconAction: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 4,
    color: "var(--text-muted)",
    display: "inline-flex",
  } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 12.5 } satisfies CSSProperties,
  th: {
    textAlign: "left",
    padding: "8px 10px",
    color: "var(--text-muted)",
    fontWeight: 600,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: "0.03em",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  td: {
    padding: "8px 10px",
    borderBottom: "1px solid var(--border)",
    verticalAlign: "middle",
  } satisfies CSSProperties,
  batchRow: { cursor: "pointer" } satisfies CSSProperties,
  drilldownWrap: {
    padding: "12px 14px",
    background: "var(--bg-hover)",
    borderRadius: 6,
    margin: "6px 0 12px",
  } satisfies CSSProperties,
  caseErrorMessage: {
    marginTop: 4,
    fontSize: 11,
    color: "var(--crit)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: 320,
  } satisfies CSSProperties,
} as const;
